version: '3.7'

services:
  web:
    build:
      context: ./medrec1
      dockerfile: Dockerfile.prod
    command: gunicorn medrec-docker.wsgi:application --bind 0.0.0.0:8000
#    --replicas: 3
    volumes:
      - static_volume:/medrec1/staticfiles
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:11.3-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.db

  #~ adminer:
    #~ image: adminer
    #~ restart: always
    #~ ports:
      #~ - 8080:8080

  nginx:
    #build: ./nginx
    image: nginx:alpine
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
